export default {
  login: "ZoranUTF8",
  id: 66476222,
  node_id: "MDQ6VXNlcjY2NDc2MjIy",
  avatar_url: "https://avatars.githubusercontent.com/u/66476222?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ZoranUTF8",
  html_url: "https://github.com/ZoranUTF8",
  followers_url: "https://api.github.com/users/ZoranUTF8/followers",
  following_url:
    "https://api.github.com/users/ZoranUTF8/following{/other_user}",
  gists_url: "https://api.github.com/users/ZoranUTF8/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ZoranUTF8/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ZoranUTF8/subscriptions",
  organizations_url: "https://api.github.com/users/ZoranUTF8/orgs",
  repos_url: "https://api.github.com/users/ZoranUTF8/repos",
  events_url: "https://api.github.com/users/ZoranUTF8/events{/privacy}",
  received_events_url: "https://api.github.com/users/ZoranUTF8/received_events",
  type: "User",
  site_admin: false,
  name: "Zoran",
  company: null,
  blog: "zoranjanjic-portofolio.netlify.app",
  location: null,
  email: null,
  hireable: true,
  bio: "👋 Hi, I’m Zoran Janjic\r\n👀 I’m interested in Java,JavaScript,CSS,HTML,NODE.JS,EXPRESS...\r\n🌱 I’m currently learning NODE.JS",
  twitter_username: null,
  public_repos: 56,
  public_gists: 0,
  followers: 1,
  following: 3,
  created_at: "2020-06-05T12:41:31Z",
  updated_at: "2021-11-23T17:49:09Z",
};
